config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.input_html
  get 'sign_up', to: 'users#new'
  get 'users/show/:id', to: 'users#show', as: 'user_show'

  #Routes for sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Routes for events
  get 'create_event', to: 'events#new'
  post 'events', to: 'events#create'
  get 'events', to: 'events#index'
  get 'events/show/:id/', to: 'events#show', as: 'event_show'


  root 'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.find_it(id)
    find(id)
  end

  def self.find_it_by_name(name)
    find_by_name(name)
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, dependent: :destroy
  has_many :guests, through: :invitations

  scope :previous, -> { where('date < ?', Time.zone.now) }
  scope :future, -> { where('date >= ?', Time.zone.now) }

  validates :location, presence: true
  validates :date, presence: true
  validates :description, presence: true

  def guest_list
    guests.collect(&:name).join(', ')
  end

  def guest_list=(guests_string)
    guest_names = guests_string.split(',').collect(&:strip).uniq
    new_or_found_guests = guest_names.collect { |name| User.find_or_create_by(name: name) }
    self.guests = new_or_found_guests
  end

  def self.creations(creator)
    where(creator_id: creator.id)
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :guests, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :invitations, dependent: :destroy
  has_many :attended_events, through: :invitations, dependent: :destroy
  validates :name, uniqueness: true

  def self.return_current_user(session)
    find_by(id: session)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'helper_module.rb'
  include HelperModule

  add_flash_types :danger
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    redirect_to root_path if current_user.nil?
    @event = Event.new
  end

  def index
    @future_events = Event.future
    @past_events = Event.previous
  end

  def create
    @event = current_user.events.build(event_params)
    @event.creator_id = current_user.id
    @event.save
    redirect_to root_path
  end

  def show
    @event = Event.find_it(params[:id])
    @guests = @event.guests
    @creator = User.find_it(@event.creator_id)
  end

  private

  def event_params
    params.require(:event).permit(:location, :date, :description, :guest_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create], raise: false

  def new
    redirect_to root_path unless current_user.nil?
  end

  def create
    user = User.find_it_by_name(params[:session][:name])
    if user.nil?
      # flash[:danger] = []
      # flash.now[:danger] << 'Invalid name' unless params[:session][:name].split
      # flash.now[:danger] << 'Name cannot be blank' if params[:session][:name].split.empty?
      redirect_to login_path, danger: 'Invalid name' unless params[:session][:name].split.empty?
      redirect_to login_path, danger: 'Name cannot be blank' if params[:session][:name].split.empty?
    else
      log_in user
      remember user
      redirect_to root_path
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    redirect_to root_path if current_user.nil?

    @user = User.find(params[:id])
    @created_by_user = Event.creations(@user)
    @past_events = get_past_events(@user)
    @future_events = get_future_events(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
      redirect_to root_path
    else
      respond_to do |f|
        f.html { render :new }
        f.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def get_past_events(user)
    past_event = []
    Event.previous.each { |event| past_event << event if event.guests.ids.include? user.id }
    past_event
  end

  def get_future_events(user)
    future_event = []
    Event.future.each { |event| future_event << event if event.guests.ids.include? user.id }
    future_event
  end

  def current_user
    @current_user ||= User.return_current_user(session[:user_id]) if session[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'helper_module.rb'
  include HelperModule
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |event| %>
  <%= event.input :location, :placeholder => 'Where will your event be?' %>
  <%= event.input :description, :placeholder => 'What\'s your event about?' %>
  <%= event.input :date %>
  <%= event.input :guest_list %>
  <%= event.submit 'Create event' %>
<% end %>

app/views/events/_future.html.erb
<div class="m-5">
<% if @future_events.empty? %>
  <%= "There're not future events" %>
  <%= link_to 'Create event', create_event_path %>
<% else %>
<% @future_events.each do |inv| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
  <h5 class="card-title"><%= "Event in #{inv.location } " %> </h5>
  <p class="card-text"> <%= "Event date: #{inv.date.to_formatted_s(:rfc822)}."%></p>
  <%= link_to 'View event', event_show_path(inv)  %>
  </div>
</div>
<% end %>
<% end %>
</div>

app/views/events/_past.html.erb
<div class="m-5">
<% if @past_events.empty? %>
  <%= "There're no previous events" %>
<% else %>
<% @past_events.each do |inv| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= "Event in #{inv.location } " %> </h5>
      <p class="card-text"> <%= "at #{inv.date.to_formatted_s(:rfc822)}." %></p>
      <%= link_to 'View event', event_show_path(inv)  %>
  </div>
</div>
<% end %>
<% end %>
</div>

app/views/events/index.html.erb
<h5>Next events:</h5>

<%= render 'future' %>

<h5>Past events</h5>

<%= render 'past' %>

app/views/events/new.html.erb
<h1> Create an event </h1>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h2>Event</h2>
<h3>Creator:</h3>
<%= link_to "#{creator(@event).name}", user_show_path(creator(@event)) %>
<h3> Location: </h3>
<%= @event.location %>
<h3>Description:</h3>
<%= @event.description %>
<h3>Date:</h3>
<%= @event.date %>
<h3>Attendee:</h3>
<ul>
<% @guests.each do |guest| %>
  <li> <%= link_to "#{guest.name}", user_show_path(guest)  %> </li>
<% end %>
</ul>

app/views/layouts/_logged_in_btn.html.erb
<h5> <%= link_to "Hello, #{current_user.name}", user_show_path(current_user), class: "text-light mr-3" %></h5>
      <%= link_to 'New event', create_event_path, class: "btn btn-lg btn-outline-light mr-3 " %>
      <%= link_to 'Log Out', logout_path, method: :delete, class: "btn btn-lg btn-outline-light" %>

app/views/layouts/_logged_off_btn.html.erb
<%= link_to 'Sign up', sign_up_path, class: "btn btn-lg btn-outline-light mr-3" %>
<%= link_to 'Log In', login_path, class: "btn btn-lg btn-outline-light " %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-inverse navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Private Events', root_path, class: "navbar-brand btn btn-lg btn-outline-light" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="d-inline-flex align-items-center ">

      <% if logged_in? %>
      <h5> <%= link_to "Hello, #{current_user.name}", user_show_path(current_user), class: "text-light mr-3" %></h5>
      <%= link_to 'New event', create_event_path, class: "btn btn-lg btn-outline-light mr-3 " %>
      <%= link_to 'Log Out', logout_path, method: :delete, class: "btn btn-lg btn-outline-light" %>
      <% else %>
       <%= link_to 'Sign up', sign_up_path, class: "btn btn-lg btn-outline-light mr-3" %>
       <%= link_to 'Log In', login_path, class: "btn btn-lg btn-outline-light " %>
      <% end %>
      </li>

    </ul>
  </div>
</nav>
  <div class="container d-flex justify-content-center align-items-center">
    <div class="col-8 justify-content-center">
      <%= yield %>
    </div>
  </div>
  <footer class="footer page-footer font-small pt-4">
<div class="container-fluid text-center">
  Created by P.H.F.Donda & J.P.Perez-Tejada
</div>
 </footer>
  </body>
</html>

app/views/users/_attending.html.erb
  <h5>Future events:</h5>

  <%= render 'future', type: 'user attending' %>

  <h5> Previous events:</h5>

  <%= render 'past', type: 'user attending %>

app/views/users/_created.html.erb
<div class="p-4">

<% if @created_by_user.empty? %>
  <%= "There're no events created by #{@user.name}" %>
<% else %>
<% @created_by_user.each do |event| %>
<div class="card mb-2 " style="width: 18rem;">
  <div class="card-body">
  <h5 class="card-title"><%= "#{@user.name} created an event in #{event.location} " %> </h5>
  <p class="card-text"> <%= "Event date: #{event.date}." %></p>
  <%= link_to 'View event', event_show_path(event)  %>
  </div>
</div>
<% end %>
<% end %>

</div>

app/views/users/_form.html.erb
<div class="form-group justify-content-center">
<%= simple_form_for(@user) do |f| %>
<%= f.error_notification %>
<div class="form-row justify-content-center">
  <div class="control">
    <%= f.input :name, label: 'Add an username', input_html: { class: 'form-control'}, wrapper: false, label_html: { class: "form-check-label"}, placeholder: "Create a new user" %>
  </div>
</div>
<div class="form-row justify-content-center">
<%= f.button :submit, class: 'btn btn-primary mt-3' %>
</div>
<% end %>
</div>

app/views/users/_future.html.erb
<div class="p-4">
<% if @future_events.empty? %>
  <%= "There're no future events" %>
<% else %>
<% @future_events.each do |inv| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
  <h5 class="card-title"><%= "#{@user.name} is invited to an event in #{inv.location } " %> </h5>
  <p class="card-text"> <%= "Event date: #{inv.date.to_formatted_s(:rfc822)}." %></p>
  <%= link_to 'View event', event_show_path(inv)  %>
  </div>
</div>
<% end %>
<% end %>
</div>

app/views/users/_past.html.erb
<div class="p-4">
<% if @past_events.empty? %>
  <%= "There're no previous events" %>
<% else %>
<% @past_events.each do |inv| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
  <h5 class="card-title"><%= "#{@user.name} was invited to an event in #{inv.location } " %> </h5>
  <p class="card-text"> <%= "Event date: #{inv.date.to_formatted_s(:rfc822)}." %></p>
  <%= link_to 'Check event', event_show_path(inv)  %>
  </div>
</div>
<% end %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="d-flex justify-content-center flex-column">
<div class="col col-6 mx-auto mt-5">

<h2 class="d-flex justify-content-center">Create a new user</h2>

<%= render 'form', user: @user %>
</div>
</div>

app/views/users/show.html.erb
<% if @current_user %>

  <h4> Created events</h4>

  <%= render 'created' %>

  <h4>Future events:</h4>

  <%= render 'future' %>

  <h4> Previous events:</h4>

  <%= render 'past' %>

<% end %>